"""add_user_avatar_and_attendance_geolocation

Revision ID: 79a3ea6791b0
Revises: add_clinical_record_history
Create Date: 2026-01-10 04:33:17.558408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79a3ea6791b0'
down_revision: Union[str, None] = 'add_clinical_record_history'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add new columns only - skip table drops and constraint changes for SQLite compatibility
    # Attendance geolocation columns
    op.add_column('attendance', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.add_column('attendance', sa.Column('clock_in_latitude', sa.Float(), nullable=True))
    op.add_column('attendance', sa.Column('clock_in_longitude', sa.Float(), nullable=True))
    op.add_column('attendance', sa.Column('clock_out_latitude', sa.Float(), nullable=True))
    op.add_column('attendance', sa.Column('clock_out_longitude', sa.Float(), nullable=True))
    op.add_column('attendance', sa.Column('clock_in_within_geofence', sa.Boolean(), nullable=True))
    op.add_column('attendance', sa.Column('clock_out_within_geofence', sa.Boolean(), nullable=True))
    
    # Branch geolocation and work hours settings
    op.add_column('branches', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('branches', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('branches', sa.Column('geofence_radius', sa.Integer(), nullable=True))
    op.add_column('branches', sa.Column('work_start_time', sa.Time(), nullable=True))
    op.add_column('branches', sa.Column('work_end_time', sa.Time(), nullable=True))
    op.add_column('branches', sa.Column('late_threshold_minutes', sa.Integer(), nullable=True))
    op.add_column('branches', sa.Column('require_geolocation', sa.Boolean(), nullable=True))
    
    # Permission code column
    op.add_column('permissions', sa.Column('code', sa.String(length=100), nullable=True))
    
    # Role default page
    op.add_column('roles', sa.Column('default_page', sa.String(length=100), nullable=True))
    
    # User avatar and last login
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visits_visit_number'), table_name='visits')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'avatar_url')
    op.drop_index(op.f('ix_technicians_id'), table_name='technicians')
    op.alter_column('technicians', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('roles', 'default_page')
    op.drop_constraint(None, 'permissions', type_='unique')
    op.drop_column('permissions', 'code')
    op.drop_column('branches', 'require_geolocation')
    op.drop_column('branches', 'late_threshold_minutes')
    op.drop_column('branches', 'work_end_time')
    op.drop_column('branches', 'work_start_time')
    op.drop_column('branches', 'geofence_radius')
    op.drop_column('branches', 'longitude')
    op.drop_column('branches', 'latitude')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_column('attendance', 'clock_out_within_geofence')
    op.drop_column('attendance', 'clock_in_within_geofence')
    op.drop_column('attendance', 'clock_out_longitude')
    op.drop_column('attendance', 'clock_out_latitude')
    op.drop_column('attendance', 'clock_in_longitude')
    op.drop_column('attendance', 'clock_in_latitude')
    op.drop_column('attendance', 'branch_id')
    op.create_table('invoice_payments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('receipt_number', sa.VARCHAR(length=30), nullable=True),
    sa.Column('invoice_id', sa.INTEGER(), nullable=True),
    sa.Column('patient_id', sa.INTEGER(), nullable=True),
    sa.Column('branch_id', sa.INTEGER(), nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=13), nullable=False),
    sa.Column('reference', sa.VARCHAR(length=100), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('received_by_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoice_payments_receipt_number', 'invoice_payments', ['receipt_number'], unique=1)
    op.create_index('ix_invoice_payments_id', 'invoice_payments', ['id'], unique=False)
    op.create_table('order_status_history',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('updated_by_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['glasses_orders.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(length=30), nullable=True),
    sa.Column('visit_id', sa.INTEGER(), nullable=True),
    sa.Column('patient_id', sa.INTEGER(), nullable=True),
    sa.Column('branch_id', sa.INTEGER(), nullable=True),
    sa.Column('subtotal', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('discount', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('tax', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('amount_paid', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('balance', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.VARCHAR(length=8), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoices_invoice_number', 'invoices', ['invoice_number'], unique=1)
    op.create_index('ix_invoices_id', 'invoices', ['id'], unique=False)
    op.create_table('visioncare_members',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('member_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('company', sa.VARCHAR(length=200), nullable=True),
    sa.Column('plan_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('valid_from', sa.DATETIME(), nullable=True),
    sa.Column('valid_until', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_visioncare_members_member_id', 'visioncare_members', ['member_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('key', sa.VARCHAR(length=100), nullable=False),
    sa.Column('value', sa.TEXT(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_by_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revenues',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), server_default=sa.text("'other'"), nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=50), server_default=sa.text("'cash'"), nullable=True),
    sa.Column('reference_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('reference_id', sa.INTEGER(), nullable=True),
    sa.Column('patient_id', sa.INTEGER(), nullable=True),
    sa.Column('branch_id', sa.INTEGER(), nullable=True),
    sa.Column('recorded_by_id', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('glasses_orders',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('order_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('patient_id', sa.INTEGER(), nullable=False),
    sa.Column('prescription_id', sa.INTEGER(), nullable=True),
    sa.Column('visit_id', sa.INTEGER(), nullable=True),
    sa.Column('lens_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('lens_material', sa.VARCHAR(length=100), nullable=True),
    sa.Column('lens_coating', sa.VARCHAR(length=200), nullable=True),
    sa.Column('frame_brand', sa.VARCHAR(length=100), nullable=True),
    sa.Column('frame_model', sa.VARCHAR(length=100), nullable=True),
    sa.Column('frame_color', sa.VARCHAR(length=50), nullable=True),
    sa.Column('frame_size', sa.VARCHAR(length=50), nullable=True),
    sa.Column('sphere_od', sa.VARCHAR(length=20), nullable=True),
    sa.Column('cylinder_od', sa.VARCHAR(length=20), nullable=True),
    sa.Column('axis_od', sa.VARCHAR(length=20), nullable=True),
    sa.Column('add_od', sa.VARCHAR(length=20), nullable=True),
    sa.Column('sphere_os', sa.VARCHAR(length=20), nullable=True),
    sa.Column('cylinder_os', sa.VARCHAR(length=20), nullable=True),
    sa.Column('axis_os', sa.VARCHAR(length=20), nullable=True),
    sa.Column('add_os', sa.VARCHAR(length=20), nullable=True),
    sa.Column('pd', sa.VARCHAR(length=20), nullable=True),
    sa.Column('lens_price', sa.DECIMAL(precision=10, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('frame_price', sa.DECIMAL(precision=10, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('total_price', sa.DECIMAL(precision=10, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('deposit_paid', sa.DECIMAL(precision=10, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('balance', sa.DECIMAL(precision=10, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('order_date', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expected_date', sa.DATE(), nullable=True),
    sa.Column('ready_date', sa.DATETIME(), nullable=True),
    sa.Column('delivery_date', sa.DATETIME(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('special_instructions', sa.TEXT(), nullable=True),
    sa.Column('branch_id', sa.INTEGER(), nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
